[package]
name = "status_code"
version = "0.1.0"
authors = ["necroplankton <necroplankton@rainy.me>"]
description = "statuses in rust."
license = "MIT"
repository = "https://github.com/necroplankton/status_code"